import { HomeHero } from "@/components/home/home-hero"
import Home from "@/components/home/home"
import { ContinueWatchingItem } from "@/types/firebase.types"
import { Film, Genre, HeroData, Network } from "@/types/tmdb.types"

const continueWatchingData: ContinueWatchingItem[] = [
  {
    id: "1",
    title: "Stranger Things",
    type: "tv",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&q=80",
    progress: 65,
    duration: "45m left",
    episode: 5,
    season: 4,
    year: 2022,
    rating: "TV-14",
  },
  {
    id: "2",
    title: "The Dark Knight",
    type: "movie",
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500&q=80",
    progress: 30,
    duration: "1h 45m left",
    year: 2008,
    rating: "PG-13",
  },
  {
    id: "3",
    title: "Breaking Bad",
    type: "tv",
    image: "https://images.unsplash.com/photo-1504593811423-6dd665756598?w=500&q=80",
    progress: 80,
    duration: "12m left",
    episode: 8,
    season: 5,
    year: 2013,
    rating: "TV-MA",
  },
  {
    id: "4",
    title: "Inception",
    type: "movie",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500&q=80",
    progress: 45,
    duration: "1h 20m left",
    year: 2010,
    rating: "PG-13",
  },
  {
    id: "5",
    title: "The Witcher",
    type: "tv",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&q=80",
    progress: 20,
    duration: "48m left",
    episode: 3,
    season: 3,
    year: 2023,
    rating: "TV-MA",
  },
  {
    id: "6",
    title: "Dune",
    type: "movie",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&q=80",
    progress: 55,
    duration: "1h 10m left",
    year: 2021,
    rating: "PG-13",
  },
  {
    id: "7",
    title: "House of the Dragon",
    type: "tv",
    image: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=500&q=80",
    progress: 90,
    duration: "6m left",
    episode: 10,
    season: 1,
    year: 2022,
    rating: "TV-MA",
  },
  {
    id: "8",
    title: "Interstellar",
    type: "movie",
    image: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=500&q=80",
    progress: 10,
    duration: "2h 30m left",
    year: 2014,
    rating: "PG-13",
  },
]

const becauseYouWatchedData: { title: string; films: Film[] } = {
  title: "Inception",
  films: [
    {
      id: 27205,
      adult: false,
      backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
      genre_ids: [28, 878, 12],
      original_language: "en",
      original_title: "Interstellar",
      overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 150.5,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.4,
      vote_count: 32000,
      media_type: "movie",
    },
    {
      id: 157336,
      adult: false,
      backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      genre_ids: [18, 878, 53],
      original_language: "en",
      original_title: "Tenet",
      overview: "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
      popularity: 120.3,
      poster_path: "/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
      release_date: "2020-08-22",
      title: "Tenet",
      video: false,
      vote_average: 7.2,
      vote_count: 8500,
      media_type: "movie",
    },
    {
      id: 272,
      adult: false,
      backdrop_path: "/66TuALbLYNPC5Jxd4JFgLn8K3hs.jpg",
      genre_ids: [28, 80, 18, 53],
      original_language: "en",
      original_title: "Batman Begins",
      overview: "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.",
      popularity: 95.2,
      poster_path: "/8RW2runSEc34IwKN2D1aPcJd2UL.jpg",
      release_date: "2005-06-10",
      title: "Batman Begins",
      video: false,
      vote_average: 7.7,
      vote_count: 18000,
      media_type: "movie",
    },
    {
      id: 155,
      adult: false,
      backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
      genre_ids: [28, 80, 18, 53],
      original_language: "en",
      original_title: "The Dark Knight",
      overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
      popularity: 130.4,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-16",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.5,
      vote_count: 30000,
      media_type: "movie",
    },
    {
      id: 49026,
      adult: false,
      backdrop_path: "/f6ljQGv7WnJuwBPty017oPWfqjx.jpg",
      genre_ids: [28, 80, 53],
      original_language: "en",
      original_title: "The Dark Knight Rises",
      overview: "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is hunted by the Gotham City Police Department.",
      popularity: 88.7,
      poster_path: "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
      release_date: "2012-07-16",
      title: "The Dark Knight Rises",
      video: false,
      vote_average: 7.8,
      vote_count: 21000,
      media_type: "movie",
    },
    {
      id: 258489,
      adult: false,
      backdrop_path: "/5WP6z3iqsRg8ZWHM9Xa5GsVLKD3.jpg",
      genre_ids: [18, 53, 878],
      original_language: "en",
      original_title: "The Prestige",
      overview: "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy, full of obsession, deceit and jealousy with dangerous and deadly consequences.",
      popularity: 75.3,
      poster_path: "/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg",
      release_date: "2006-10-17",
      title: "The Prestige",
      video: false,
      vote_average: 8.2,
      vote_count: 14000,
      media_type: "movie",
    },
  ],
}

const nowShowingInTheatersData: Film[] = [
  {
    id: 693134,
    adult: false,
    backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Dune: Part Two",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    popularity: 850.5,
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.3,
    vote_count: 5200,
    media_type: "movie",
  },
  {
    id: 823464,
    adult: false,
    backdrop_path: "/417tYZ4XUyJrtyZXj7HpvWf1E8f.jpg",
    genre_ids: [16, 28, 12],
    original_language: "ja",
    original_title: "Godzilla x Kong: The New Empire",
    overview: "Following their fruit in previous adventure, the legendary titans Godzilla and Kong face a brand new threat lurking within our world.",
    popularity: 720.3,
    poster_path: "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 7.1,
    vote_count: 3100,
    media_type: "movie",
  },
  {
    id: 940721,
    adult: false,
    backdrop_path: "/kYgQzzjNis5jJalYtIHgrom0gOx.jpg",
    genre_ids: [16, 10751, 35, 14],
    original_language: "en",
    original_title: "Inside Out 2",
    overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions!",
    popularity: 950.8,
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    release_date: "2024-06-11",
    title: "Inside Out 2",
    video: false,
    vote_average: 7.8,
    vote_count: 4500,
    media_type: "movie",
  },
  {
    id: 653346,
    adult: false,
    backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview: "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows.",
    popularity: 680.2,
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    release_date: "2024-05-08",
    title: "Kingdom of the Planet of the Apes",
    video: false,
    vote_average: 7.2,
    vote_count: 2800,
    media_type: "movie",
  },
  {
    id: 1022789,
    adult: false,
    backdrop_path: "/7wv0xtEhP0mjYFdXKNqJwVBq4IQ.jpg",
    genre_ids: [16, 28, 878, 35],
    original_language: "en",
    original_title: "Despicable Me 4",
    overview: "Gru and Lucy and their girls welcome a new member to the family, Gru Jr., who is intent on tormenting his dad.",
    popularity: 580.6,
    poster_path: "/3w84hCFJATpiCNt68hZVlbSV4MF.jpg",
    release_date: "2024-06-20",
    title: "Despicable Me 4",
    video: false,
    vote_average: 7.0,
    vote_count: 1500,
    media_type: "movie",
  },
]

const romanceMoviesData: Film[] = [
  {
    id: 509,
    adult: false,
    backdrop_path: "/2Ie92LDycpAsQzWqL1DRqx41Dn.jpg",
    genre_ids: [18, 10749],
    original_language: "en",
    original_title: "Notting Hill",
    overview: "William Thacker is a London bookstore owner whose humdrum existence is thrown into romantic turmoil when famous American actress Anna Scott appears in his shop.",
    popularity: 65.3,
    poster_path: "/bGl7QxsxflrPw7E9pDPpwvJZks2.jpg",
    release_date: "1999-05-13",
    title: "Notting Hill",
    video: false,
    vote_average: 7.2,
    vote_count: 5800,
    media_type: "movie",
  },
  {
    id: 597,
    adult: false,
    backdrop_path: "/8lTMhLGdqYoScxdZqFfs5BKQJ7Z.jpg",
    genre_ids: [18, 10749],
    original_language: "en",
    original_title: "Titanic",
    overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later.",
    popularity: 110.5,
    poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    release_date: "1997-11-18",
    title: "Titanic",
    video: false,
    vote_average: 7.9,
    vote_count: 23000,
    media_type: "movie",
  },
  {
    id: 332562,
    adult: false,
    backdrop_path: "/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
    genre_ids: [10749, 18],
    original_language: "en",
    original_title: "A Star Is Born",
    overview: "Seasoned musician Jackson Maine discovers-Loss and soon falls in love with-struggling artist Ally. She has just about given up on her dream to make it big as a singer until Jackson coaxes her into the spotlight.",
    popularity: 88.2,
    poster_path: "/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
    release_date: "2018-10-03",
    title: "A Star Is Born",
    video: false,
    vote_average: 7.5,
    vote_count: 11000,
    media_type: "movie",
  },
  {
    id: 313369,
    adult: false,
    backdrop_path: "/ndlQ2Cuc3cjTL7lTynw6I4boP4S.jpg",
    genre_ids: [10749, 18],
    original_language: "en",
    original_title: "La La Land",
    overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fabric of their love affair.",
    popularity: 75.8,
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    release_date: "2016-11-29",
    title: "La La Land",
    video: false,
    vote_average: 7.9,
    vote_count: 15000,
    media_type: "movie",
  },
  {
    id: 11036,
    adult: false,
    backdrop_path: "/gL8myjGc2qrmqVosyGm5CWTir9A.jpg",
    genre_ids: [35, 18, 10749],
    original_language: "en",
    original_title: "The Notebook",
    overview: "An epic love story centered around an older man who reads aloud to a woman with Alzheimer's. From a faded notebook, the old man's words bring to life the story about a couple who is separated by World War II.",
    popularity: 82.4,
    poster_path: "/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg",
    release_date: "2004-06-25",
    title: "The Notebook",
    video: false,
    vote_average: 7.9,
    vote_count: 10500,
    media_type: "movie",
  },
  {
    id: 76341,
    adult: false,
    backdrop_path: "/nlCHUWjY9XWbuEUQauCBgnGcoe.jpg",
    genre_ids: [10749, 35],
    original_language: "en",
    original_title: "Crazy Rich Asians",
    overview: "An American-born Chinese economics professor accompanies her boyfriend to Singapore for his best friend's wedding, only to get thrust into the lives of Asia's rich and famous.",
    popularity: 68.9,
    poster_path: "/1XxL4LJ5WHdrcYcihEZUCgNCpAW.jpg",
    release_date: "2018-08-15",
    title: "Crazy Rich Asians",
    video: false,
    vote_average: 7.1,
    vote_count: 4200,
    media_type: "movie",
  },
]

const actionMoviesData: Film[] = [
  {
    id: 603692,
    adult: false,
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    genre_ids: [28, 53, 80],
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview: "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
    popularity: 310.5,
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 7.9,
    vote_count: 8500,
    media_type: "movie",
  },
  {
    id: 385687,
    adult: false,
    backdrop_path: "/bWm2kLu0EE0r8YuH3VHV0Af3s5O.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Fast X",
    overview: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted and outdriven every foe in their path. Now, they face the most lethal opponent they've ever faced.",
    popularity: 280.3,
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    video: false,
    vote_average: 7.1,
    vote_count: 5200,
    media_type: "movie",
  },
  {
    id: 640146,
    adult: false,
    backdrop_path: "/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Ant-Man and the Wasp: Quantumania",
    overview: "Super-Hero partners Scott Lang and Hope van Dyne, along with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm.",
    popularity: 250.8,
    poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    release_date: "2023-02-15",
    title: "Ant-Man and the Wasp: Quantumania",
    video: false,
    vote_average: 6.5,
    vote_count: 4800,
    media_type: "movie",
  },
  {
    id: 667538,
    adult: false,
    backdrop_path: "/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
    genre_ids: [28, 878, 27],
    original_language: "en",
    original_title: "Transformers: Rise of the Beasts",
    overview: "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals.",
    popularity: 220.6,
    poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    release_date: "2023-06-06",
    title: "Transformers: Rise of the Beasts",
    video: false,
    vote_average: 7.3,
    vote_count: 3900,
    media_type: "movie",
  },
  {
    id: 569094,
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview: "After reuniting with Gwen Stacy, Brooklyn's full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society.",
    popularity: 380.2,
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    title: "Spider-Man: Across the Spider-Verse",
    video: false,
    vote_average: 8.4,
    vote_count: 6200,
    media_type: "movie",
  },
  {
    id: 447365,
    adult: false,
    backdrop_path: "/t9nyF3r0WAlJ7Kr6xcRYI4jr9jm.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Guardians of the Galaxy Vol. 3",
    overview: "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own.",
    popularity: 290.4,
    poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    release_date: "2023-05-03",
    title: "Guardians of the Galaxy Vol. 3",
    video: false,
    vote_average: 8.0,
    vote_count: 5800,
    media_type: "movie",
  },
]

const popularOnAppData: Film[] = [
  {
    id: 76600,
    adult: false,
    backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
    genre_ids: [878, 12, 28],
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview: "Set more than a decade after the events of the first film, learn the story of the Sully family, the trouble that follows them, the lengths they go to keep each other safe.",
    popularity: 450.5,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.7,
    vote_count: 11000,
    media_type: "movie",
  },
  {
    id: 502356,
    adult: false,
    backdrop_path: "/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
    genre_ids: [16, 12, 10751, 14, 35],
    original_language: "en",
    original_title: "The Super Mario Bros. Movie",
    overview: "While working underground to fix a water main, Brooklyn plumbers Mario and Luigi are transported down a mysterious pipe and wander into a magical new world.",
    popularity: 380.2,
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    release_date: "2023-04-05",
    title: "The Super Mario Bros. Movie",
    video: false,
    vote_average: 7.5,
    vote_count: 8200,
    media_type: "movie",
  },
  {
    id: 315162,
    adult: false,
    backdrop_path: "/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg",
    genre_ids: [16, 10751, 14, 12, 35, 18],
    original_language: "en",
    original_title: "Puss in Boots: The Last Wish",
    overview: "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives.",
    popularity: 320.8,
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    title: "Puss in Boots: The Last Wish",
    video: false,
    vote_average: 8.3,
    vote_count: 7500,
    media_type: "movie",
  },
  {
    id: 677179,
    adult: false,
    backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
    genre_ids: [18, 28],
    original_language: "en",
    original_title: "Creed III",
    overview: "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life.",
    popularity: 280.6,
    poster_path: "/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
    release_date: "2023-03-01",
    title: "Creed III",
    video: false,
    vote_average: 7.3,
    vote_count: 4500,
    media_type: "movie",
  },
  {
    id: 594767,
    adult: false,
    backdrop_path: "/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg",
    genre_ids: [28, 35, 14],
    original_language: "en",
    original_title: "Shazam! Fury of the Gods",
    overview: "Billy Batson and his foster siblings, who transform into superheroes by saying 'Shazam!', are forced to get back into action.",
    popularity: 250.3,
    poster_path: "/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
    release_date: "2023-03-15",
    title: "Shazam! Fury of the Gods",
    video: false,
    vote_average: 6.8,
    vote_count: 3800,
    media_type: "movie",
  },
  {
    id: 94997,
    adult: false,
    backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    genre_ids: [10765, 18, 10759],
    original_language: "en",
    original_name: "House of the Dragon",
    overview: "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke.",
    popularity: 420.5,
    poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    first_air_date: "2022-08-21",
    name: "House of the Dragon",
    vote_average: 8.4,
    vote_count: 4200,
    media_type: "tv",
  },
  {
    id: 1396,
    adult: false,
    backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
    genre_ids: [18, 80],
    original_language: "en",
    original_name: "Breaking Bad",
    overview: "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live.",
    popularity: 380.8,
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    first_air_date: "2008-01-20",
    name: "Breaking Bad",
    vote_average: 8.9,
    vote_count: 12000,
    media_type: "tv",
  },
  {
    id: 66732,
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    genre_ids: [18, 10765],
    original_language: "en",
    original_name: "Stranger Things",
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    popularity: 350.2,
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    first_air_date: "2016-07-15",
    name: "Stranger Things",
    vote_average: 8.6,
    vote_count: 16000,
    media_type: "tv",
  },
]

const genresData: Genre[] = [
  { id: 28, name: "Action", image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500&q=80" },
  { id: 12, name: "Adventure", image: "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=500&q=80" },
  { id: 16, name: "Animation", image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&q=80" },
  { id: 35, name: "Comedy", image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=500&q=80" },
  { id: 80, name: "Crime", image: "https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=500&q=80" },
  { id: 99, name: "Documentary", image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500&q=80" },
  { id: 18, name: "Drama", image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&q=80" },
  { id: 10751, name: "Family", image: "https://images.unsplash.com/photo-1594897030264-ab7d87efc473?w=500&q=80" },
  { id: 14, name: "Fantasy", image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&q=80" },
  { id: 36, name: "History", image: "https://images.unsplash.com/photo-1461360370896-922624d12a74?w=500&q=80" },
  { id: 27, name: "Horror", image: "https://images.unsplash.com/photo-1509248961725-9d3d73e7adca?w=500&q=80" },
  { id: 10402, name: "Music", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&q=80" },
  { id: 9648, name: "Mystery", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80" },
  { id: 10749, name: "Romance", image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=500&q=80" },
  { id: 878, name: "Sci-Fi", image: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=500&q=80" },
  { id: 53, name: "Thriller", image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&q=80" },
]

const upcomingMoviesData: Film[] = [
  {
    id: 912649,
    adult: false,
    backdrop_path: "/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg",
    genre_ids: [16, 10751, 35, 12],
    original_language: "en",
    original_title: "Moana 2",
    overview: "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
    popularity: 520.8,
    poster_path: "/4YZpsylmjHbqeWzjKpUEF8gcLNW.jpg",
    release_date: "2025-11-27",
    title: "Moana 2",
    video: false,
    vote_average: 0,
    vote_count: 0,
    media_type: "movie",
  },
  {
    id: 668489,
    adult: false,
    backdrop_path: "/fY3lD0jM5AoHJMunjGWqJ0hRteI.jpg",
    genre_ids: [878, 12, 28],
    original_language: "en",
    original_title: "Superman",
    overview: "Superman, a cub reporter in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
    popularity: 480.5,
    poster_path: "/d7PIR3cAMsLzEzUbP2hqJy3LyI1.jpg",
    release_date: "2025-07-11",
    title: "Superman",
    video: false,
    vote_average: 0,
    vote_count: 0,
    media_type: "movie",
  },
  {
    id: 1064028,
    adult: false,
    backdrop_path: "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
    genre_ids: [28, 878, 12],
    original_language: "en",
    original_title: "Captain America: Brave New World",
    overview: "Sam Wilson, who is now the new Captain America, finds himself in the middle of an international incident and must discover the motive behind a nefarious global plot.",
    popularity: 420.3,
    poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
    release_date: "2025-02-14",
    title: "Captain America: Brave New World",
    video: false,
    vote_average: 0,
    vote_count: 0,
    media_type: "movie",
  },
  {
    id: 950387,
    adult: false,
    backdrop_path: "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
    genre_ids: [27, 9648, 53],
    original_language: "en",
    original_title: "A Quiet Place: Day One",
    overview: "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
    popularity: 380.6,
    poster_path: "/hU42CRk14JuPEdqZG3AWmagiPAP.jpg",
    release_date: "2025-06-28",
    title: "A Quiet Place: Day One",
    video: false,
    vote_average: 0,
    vote_count: 0,
    media_type: "movie",
  },
  {
    id: 986056,
    adult: false,
    backdrop_path: "/45zVtZx6Tzx3RKeDziK5NsGDPpm.jpg",
    genre_ids: [28, 878, 12],
    original_language: "en",
    original_title: "Thunderbolts",
    overview: "A group of antiheroes are recruited by the government to go on dangerous missions.",
    popularity: 350.2,
    poster_path: "/gQa28VnHNBNq9lPtSxFI2vqjBKz.jpg",
    release_date: "2025-05-02",
    title: "Thunderbolts",
    video: false,
    vote_average: 0,
    vote_count: 0,
    media_type: "movie",
  },
  {
    id: 1001311,
    adult: false,
    backdrop_path: "/6Wdl9N6dL0Hi0T1qJLWSz6gMLbd.jpg",
    genre_ids: [28, 12, 53],
    original_language: "en",
    original_title: "Mission: Impossible – The Final Reckoning",
    overview: "Ethan Hunt and the IMF team must track down a terrifying new weapon that threatens all of humanity.",
    popularity: 320.8,
    poster_path: "/z0gMfqfyU6VR5a6LjTHG8b2MWDQ.jpg",
    release_date: "2025-05-23",
    title: "Mission: Impossible – The Final Reckoning",
    video: false,
    vote_average: 0,
    vote_count: 0,
    media_type: "movie",
  },
]

const networksData: Network[] = [
  {
    id: 213,
    name: "Netflix",
    logo_path: "/wwemzKWzjKYJFfCeiB57q3r4Bcm.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=500&q=80",
  },
  {
    id: 2739,
    name: "Disney+",
    logo_path: "/gJ8VX6JSu3ciXHuC2dDGAo2lvwM.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1640499900704-b00dd6a1103a?w=500&q=80",
  },
  {
    id: 1024,
    name: "Amazon Prime Video",
    logo_path: "/ifhbNuuVnlwYy5oXA5VIb2YR8AZ.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1521747116042-5a810fda9664?w=500&q=80",
  },
  {
    id: 49,
    name: "HBO",
    logo_path: "/tuomPhY2UtuPTqqFnKMVHvSb724.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&q=80",
  },
  {
    id: 2552,
    name: "Apple TV+",
    logo_path: "/4KAy34EHvRM25Ih8wb82AuGU7zJ.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=500&q=80",
  },
  {
    id: 453,
    name: "Hulu",
    logo_path: "/pqUTCleNUiTLAVlelGxUgWn1ELh.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=500&q=80",
  },
  {
    id: 359,
    name: "Paramount+",
    logo_path: "/fi83B1ozxPKASQmYlT9ZfIyPBKp.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500&q=80",
  },
  {
    id: 174,
    name: "AMC",
    logo_path: "/fl8DHLlW2cNxbKj01D1zXaFNvho.png",
    origin_country: "US",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&q=80",
  },
]

const heroData: HeroData = {
  id: 693134,
  title: "Dune: Part Two",
  overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
  backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
  poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
  release_date: "2024-02-27",
  vote_average: 8.3,
  genres: ["Action", "Adventure", "Sci-Fi"],
  runtime: 166,
  certification: "PG-13",
  media_type: "movie",
  video_key: "Way9Dexny3w",
}

export default function page() {
  return (
    <>
      <HomeHero data={heroData} />
      <Home
        continueWatch={continueWatchingData}
        becauseYouWatched={becauseYouWatchedData}
        nowShowingInTheaters={nowShowingInTheatersData}
        upcomingMovies={upcomingMoviesData}
        romanceMovies={romanceMoviesData}
        actionMovies={actionMoviesData}
        popularOnApp={popularOnAppData}
        genres={genresData}
        networks={networksData}
        heroData={heroData}
      />
    </>
  )
}
